version: '3.8'

services:
  postgres:
    container_name: nest-postgres-graphql
    image: postgres:14.5
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-min33sky}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-qwe123}
      POSTGRES_DB: ${POSTGRES_DB:-nest_auth_gql}
    volumes:
      - postgres:/var/lib/data/postgres
    ports:
      - '5432:5432'
    restart: unless-stopped

volumes:
  postgres:
    name: nest-postgres-graphql
